name: first_proj
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  cupertino_icons: ^1.0.2
  weather: ^3.1.1
  http: 1.2.0
  geolocator: ^10.1.0
  permission_handler: ^10.3.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png
    - lib/assets/event1.jpg
    - lib/assets/event2.jpg
    - lib/assets/event3.jpg
    - lib/assets/news1.jpg
    - lib/assets/news2.jpg
    - lib/assets/news3.jpg
    - lib/assets/backgrnd.png
    - lib/assets/blog1.jpg
    - lib/assets/blog2.jpg
    - lib/assets/blog3.jpg
    - lib/assets/ferti1.jpg 
    - lib/assets/ferti2.jpg 
    - lib/assets/ferti3.jpg 
    - lib/assets/market1.jpg
    - lib/assets/market2.png 
    - lib/assets/market3.jpg

